server:
  port: 9803 # 服务端口
  servlet:
    context-path: /
# 应用名称
spring:
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
  application:
    name: monster-security
  datasource:
    # 数据库驱动：
    driver-class-name: com.mysql.cj.jdbc.Driver
    # 数据源名称
    name: defaultDataSource
    # 数据库连接地址
    url: jdbc:mysql://localhost:3306/monster_security?serverTimezone=UTC&allowMultiQueries=true
    # 数据库用户名&密码：
    username: root
    password: root

eureka:
  client:
    service-url:
      # eureka的地址信息（因为eureka也是一个微服务，也要注册到注册中心里）
      defaultZone: http://localhost:9801/eureka
  instance:
    prefer-ip-address: true

mybatis-plus:
  # 配置 Mapper 扫描路径
  mapper-locations: classpath:mapper/**/*.xml
  # 实体类所在包（用于别名配置）
  type-aliases-package: com.monster.security.core.bean
  configuration:
    # 开启驼峰命名映射
    map-underscore-to-camel-case: true
    # 日志输出（开发环境开启）
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      # 全局主键策略（默认雪花算法）
      id-type: ASSIGN_ID
      # 逻辑删除字段名（可选）
      logic-delete-field: deleted
      # 逻辑删除值（1=删除，0=未删除）
      logic-delete-value: 1
      logic-not-delete-value: 0